language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - psql -c 'create database testdb;' -U postgres

script: phpunit --configuration phpunit.xml --coverage-text

php:
  - 5.3
  - 5.4